//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client_Diagnostic.refwcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Enums : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string allField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_Client_Diagnostic.refwcf.fueltypeenum fueltypeenumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string all {
            get {
                return this.allField;
            }
            set {
                if ((object.ReferenceEquals(this.allField, value) != true)) {
                    this.allField = value;
                    this.RaisePropertyChanged("all");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Client_Diagnostic.refwcf.fueltypeenum fueltypeenum {
            get {
                return this.fueltypeenumField;
            }
            set {
                if ((this.fueltypeenumField.Equals(value) != true)) {
                    this.fueltypeenumField = value;
                    this.RaisePropertyChanged("fueltypeenum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fueltypeenum", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    public enum fueltypeenum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PB = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LPG = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diesel = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="refwcf.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WCF_Client_Diagnostic.refwcf.CompositeType GetDataUsingDataContract(WCF_Client_Diagnostic.refwcf.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCF_Client_Diagnostic.refwcf.CompositeType> GetDataUsingDataContractAsync(WCF_Client_Diagnostic.refwcf.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        bool Authentication(string loginNamecrypt, string passwordcrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        System.Threading.Tasks.Task<bool> AuthenticationAsync(string loginNamecrypt, string passwordcrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fueltypeget", ReplyAction="http://tempuri.org/IService1/fueltypegetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCF_Client_Diagnostic.refwcf.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCF_Client_Diagnostic.refwcf.Enums))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCF_Client_Diagnostic.refwcf.fueltypeenum))]
        object fueltypeget(WCF_Client_Diagnostic.refwcf.Enums all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/fueltypeget", ReplyAction="http://tempuri.org/IService1/fueltypegetResponse")]
        System.Threading.Tasks.Task<object> fueltypegetAsync(WCF_Client_Diagnostic.refwcf.Enums all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstartwork", ReplyAction="http://tempuri.org/IService1/getstartworkResponse")]
        string getstartwork(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstartwork", ReplyAction="http://tempuri.org/IService1/getstartworkResponse")]
        System.Threading.Tasks.Task<string> getstartworkAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Business_employe", ReplyAction="http://tempuri.org/IService1/Business_employeResponse")]
        System.Data.DataSet Business_employe(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Business_employe", ReplyAction="http://tempuri.org/IService1/Business_employeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Business_employeAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowReviewsTable", ReplyAction="http://tempuri.org/IService1/ShowReviewsTableResponse")]
        System.Data.DataSet ShowReviewsTable(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowReviewsTable", ReplyAction="http://tempuri.org/IService1/ShowReviewsTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowReviewsTableAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowRepairTable", ReplyAction="http://tempuri.org/IService1/ShowRepairTableResponse")]
        System.Data.DataSet ShowRepairTable(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowRepairTable", ReplyAction="http://tempuri.org/IService1/ShowRepairTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowRepairTableAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOrderTable", ReplyAction="http://tempuri.org/IService1/ShowOrderTableResponse")]
        System.Data.DataSet ShowOrderTable(string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOrderTable", ReplyAction="http://tempuri.org/IService1/ShowOrderTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowOrderTableAsync(string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewReview", ReplyAction="http://tempuri.org/IService1/NewReviewResponse")]
        string NewReview(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewReview", ReplyAction="http://tempuri.org/IService1/NewReviewResponse")]
        System.Threading.Tasks.Task<string> NewReviewAsync(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Client_Diagnostic.refwcf.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Client_Diagnostic.refwcf.IService1>, WCF_Client_Diagnostic.refwcf.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCF_Client_Diagnostic.refwcf.CompositeType GetDataUsingDataContract(WCF_Client_Diagnostic.refwcf.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCF_Client_Diagnostic.refwcf.CompositeType> GetDataUsingDataContractAsync(WCF_Client_Diagnostic.refwcf.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool Authentication(string loginNamecrypt, string passwordcrypt) {
            return base.Channel.Authentication(loginNamecrypt, passwordcrypt);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticationAsync(string loginNamecrypt, string passwordcrypt) {
            return base.Channel.AuthenticationAsync(loginNamecrypt, passwordcrypt);
        }
        
        public object fueltypeget(WCF_Client_Diagnostic.refwcf.Enums all) {
            return base.Channel.fueltypeget(all);
        }
        
        public System.Threading.Tasks.Task<object> fueltypegetAsync(WCF_Client_Diagnostic.refwcf.Enums all) {
            return base.Channel.fueltypegetAsync(all);
        }
        
        public string getstartwork(string name) {
            return base.Channel.getstartwork(name);
        }
        
        public System.Threading.Tasks.Task<string> getstartworkAsync(string name) {
            return base.Channel.getstartworkAsync(name);
        }
        
        public System.Data.DataSet Business_employe(string login) {
            return base.Channel.Business_employe(login);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Business_employeAsync(string login) {
            return base.Channel.Business_employeAsync(login);
        }
        
        public System.Data.DataSet ShowReviewsTable(string VIN) {
            return base.Channel.ShowReviewsTable(VIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowReviewsTableAsync(string VIN) {
            return base.Channel.ShowReviewsTableAsync(VIN);
        }
        
        public System.Data.DataSet ShowRepairTable(string VIN) {
            return base.Channel.ShowRepairTable(VIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowRepairTableAsync(string VIN) {
            return base.Channel.ShowRepairTableAsync(VIN);
        }
        
        public System.Data.DataSet ShowOrderTable(string BusinessName) {
            return base.Channel.ShowOrderTable(BusinessName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowOrderTableAsync(string BusinessName) {
            return base.Channel.ShowOrderTableAsync(BusinessName);
        }
        
        public string NewReview(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel) {
            return base.Channel.NewReview(WhoReviewsBusinessName, WhereReviewsBusinessName, Mileage, Colour, WhoReviewEmployee, Brakes, Damper, Exhaust, Convergence, light, Vin, fuel);
        }
        
        public System.Threading.Tasks.Task<string> NewReviewAsync(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel) {
            return base.Channel.NewReviewAsync(WhoReviewsBusinessName, WhereReviewsBusinessName, Mileage, Colour, WhoReviewEmployee, Brakes, Damper, Exhaust, Convergence, light, Vin, fuel);
        }
    }
}
