//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckVinClient.WCFVIN {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Enums : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CheckVinClient.WCFVIN.Fueltypeenum FueltypeenumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string All {
            get {
                return this.AllField;
            }
            set {
                if ((object.ReferenceEquals(this.AllField, value) != true)) {
                    this.AllField = value;
                    this.RaisePropertyChanged("All");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CheckVinClient.WCFVIN.Fueltypeenum Fueltypeenum {
            get {
                return this.FueltypeenumField;
            }
            set {
                if ((this.FueltypeenumField.Equals(value) != true)) {
                    this.FueltypeenumField = value;
                    this.RaisePropertyChanged("Fueltypeenum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fueltypeenum", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    public enum Fueltypeenum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PB = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LPG = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diesel = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrakesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConvergenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DamperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExhaustField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhereReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoReviewEnployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoReviewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brakes {
            get {
                return this.BrakesField;
            }
            set {
                if ((object.ReferenceEquals(this.BrakesField, value) != true)) {
                    this.BrakesField = value;
                    this.RaisePropertyChanged("Brakes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Convergence {
            get {
                return this.ConvergenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvergenceField, value) != true)) {
                    this.ConvergenceField = value;
                    this.RaisePropertyChanged("Convergence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Damper {
            get {
                return this.DamperField;
            }
            set {
                if ((object.ReferenceEquals(this.DamperField, value) != true)) {
                    this.DamperField = value;
                    this.RaisePropertyChanged("Damper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateReviews {
            get {
                return this.DateReviewsField;
            }
            set {
                if ((this.DateReviewsField.Equals(value) != true)) {
                    this.DateReviewsField = value;
                    this.RaisePropertyChanged("DateReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exhaust {
            get {
                return this.ExhaustField;
            }
            set {
                if ((object.ReferenceEquals(this.ExhaustField, value) != true)) {
                    this.ExhaustField = value;
                    this.RaisePropertyChanged("Exhaust");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelField, value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Light {
            get {
                return this.LightField;
            }
            set {
                if ((object.ReferenceEquals(this.LightField, value) != true)) {
                    this.LightField = value;
                    this.RaisePropertyChanged("Light");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((object.ReferenceEquals(this.MileageField, value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vin {
            get {
                return this.VinField;
            }
            set {
                if ((object.ReferenceEquals(this.VinField, value) != true)) {
                    this.VinField = value;
                    this.RaisePropertyChanged("Vin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhereReviews {
            get {
                return this.WhereReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.WhereReviewsField, value) != true)) {
                    this.WhereReviewsField = value;
                    this.RaisePropertyChanged("WhereReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoReviewEnployee {
            get {
                return this.WhoReviewEnployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoReviewEnployeeField, value) != true)) {
                    this.WhoReviewEnployeeField = value;
                    this.RaisePropertyChanged("WhoReviewEnployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoReviews {
            get {
                return this.WhoReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoReviewsField, value) != true)) {
                    this.WhoReviewsField = value;
                    this.RaisePropertyChanged("WhoReviews");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Repair", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Repair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepairDescritionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplacedPartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhereRepairbusinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoRepairEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoRepairbusinessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cost {
            get {
                return this.CostField;
            }
            set {
                if ((object.ReferenceEquals(this.CostField, value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((object.ReferenceEquals(this.MileageField, value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepairDescrition {
            get {
                return this.RepairDescritionField;
            }
            set {
                if ((object.ReferenceEquals(this.RepairDescritionField, value) != true)) {
                    this.RepairDescritionField = value;
                    this.RaisePropertyChanged("RepairDescrition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplacedParts {
            get {
                return this.ReplacedPartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplacedPartsField, value) != true)) {
                    this.ReplacedPartsField = value;
                    this.RaisePropertyChanged("ReplacedParts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhereRepairbusiness {
            get {
                return this.WhereRepairbusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.WhereRepairbusinessField, value) != true)) {
                    this.WhereRepairbusinessField = value;
                    this.RaisePropertyChanged("WhereRepairbusiness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoRepairEmployee {
            get {
                return this.WhoRepairEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoRepairEmployeeField, value) != true)) {
                    this.WhoRepairEmployeeField = value;
                    this.RaisePropertyChanged("WhoRepairEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoRepairbusiness {
            get {
                return this.WhoRepairbusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoRepairbusinessField, value) != true)) {
                    this.WhoRepairbusinessField = value;
                    this.RaisePropertyChanged("WhoRepairbusiness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WhenDateNecessaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhereOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoOrderBusinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoOrderEmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSend {
            get {
                return this.DateSendField;
            }
            set {
                if ((this.DateSendField.Equals(value) != true)) {
                    this.DateSendField = value;
                    this.RaisePropertyChanged("DateSend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Send {
            get {
                return this.SendField;
            }
            set {
                if ((object.ReferenceEquals(this.SendField, value) != true)) {
                    this.SendField = value;
                    this.RaisePropertyChanged("Send");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WhenDateNecessary {
            get {
                return this.WhenDateNecessaryField;
            }
            set {
                if ((this.WhenDateNecessaryField.Equals(value) != true)) {
                    this.WhenDateNecessaryField = value;
                    this.RaisePropertyChanged("WhenDateNecessary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhereOrder {
            get {
                return this.WhereOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.WhereOrderField, value) != true)) {
                    this.WhereOrderField = value;
                    this.RaisePropertyChanged("WhereOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoOrderBusiness {
            get {
                return this.WhoOrderBusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoOrderBusinessField, value) != true)) {
                    this.WhoOrderBusinessField = value;
                    this.RaisePropertyChanged("WhoOrderBusiness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoOrderEmployee {
            get {
                return this.WhoOrderEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoOrderEmployeeField, value) != true)) {
                    this.WhoOrderEmployeeField = value;
                    this.RaisePropertyChanged("WhoOrderEmployee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class Bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformationClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ReceivedCashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypePaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhereBusinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoBillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoBusinessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformationClient {
            get {
                return this.InformationClientField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationClientField, value) != true)) {
                    this.InformationClientField = value;
                    this.RaisePropertyChanged("InformationClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ReceivedCash {
            get {
                return this.ReceivedCashField;
            }
            set {
                if ((this.ReceivedCashField.Equals(value) != true)) {
                    this.ReceivedCashField = value;
                    this.RaisePropertyChanged("ReceivedCash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Rest {
            get {
                return this.RestField;
            }
            set {
                if ((this.RestField.Equals(value) != true)) {
                    this.RestField = value;
                    this.RaisePropertyChanged("Rest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypePayment {
            get {
                return this.TypePaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.TypePaymentField, value) != true)) {
                    this.TypePaymentField = value;
                    this.RaisePropertyChanged("TypePayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string What {
            get {
                return this.WhatField;
            }
            set {
                if ((object.ReferenceEquals(this.WhatField, value) != true)) {
                    this.WhatField = value;
                    this.RaisePropertyChanged("What");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhereBusiness {
            get {
                return this.WhereBusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.WhereBusinessField, value) != true)) {
                    this.WhereBusinessField = value;
                    this.RaisePropertyChanged("WhereBusiness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoBill {
            get {
                return this.WhoBillField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoBillField, value) != true)) {
                    this.WhoBillField = value;
                    this.RaisePropertyChanged("WhoBill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhoBusiness {
            get {
                return this.WhoBusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoBusinessField, value) != true)) {
                    this.WhoBusinessField = value;
                    this.RaisePropertyChanged("WhoBusiness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractIServiceSendEmailOrder", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class ContractIServiceSendEmailOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateNecessaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateNecessary {
            get {
                return this.DateNecessaryField;
            }
            set {
                if ((this.DateNecessaryField.Equals(value) != true)) {
                    this.DateNecessaryField = value;
                    this.RaisePropertyChanged("DateNecessary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Who {
            get {
                return this.WhoField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoField, value) != true)) {
                    this.WhoField = value;
                    this.RaisePropertyChanged("Who");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckVinClient_Account", Namespace="http://schemas.datacontract.org/2004/07/WCFservice_diagnostic")]
    [System.SerializableAttribute()]
    public partial class CheckVinClient_Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdressEmail {
            get {
                return this.AdressEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressEmailField, value) != true)) {
                    this.AdressEmailField = value;
                    this.RaisePropertyChanged("AdressEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFVIN.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        bool Authentication(string loginNamecrypt, string passwordcrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        System.Threading.Tasks.Task<bool> AuthenticationAsync(string loginNamecrypt, string passwordcrypt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Fueltypeget", ReplyAction="http://tempuri.org/IService1/FueltypegetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Enums))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Fueltypeenum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Review))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Repair))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.Bill))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.ContractIServiceSendEmailOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckVinClient.WCFVIN.CheckVinClient_Account))]
        object Fueltypeget(CheckVinClient.WCFVIN.Enums all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Fueltypeget", ReplyAction="http://tempuri.org/IService1/FueltypegetResponse")]
        System.Threading.Tasks.Task<object> FueltypegetAsync(CheckVinClient.WCFVIN.Enums all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstartwork", ReplyAction="http://tempuri.org/IService1/getstartworkResponse")]
        string getstartwork(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstartwork", ReplyAction="http://tempuri.org/IService1/getstartworkResponse")]
        System.Threading.Tasks.Task<string> getstartworkAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Business_employe", ReplyAction="http://tempuri.org/IService1/Business_employeResponse")]
        System.Data.DataSet Business_employe(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Business_employe", ReplyAction="http://tempuri.org/IService1/Business_employeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Business_employeAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowReviewsTable", ReplyAction="http://tempuri.org/IService1/ShowReviewsTableResponse")]
        System.Data.DataSet ShowReviewsTable(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowReviewsTable", ReplyAction="http://tempuri.org/IService1/ShowReviewsTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowReviewsTableAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowRepairTable", ReplyAction="http://tempuri.org/IService1/ShowRepairTableResponse")]
        System.Data.DataSet ShowRepairTable(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowRepairTable", ReplyAction="http://tempuri.org/IService1/ShowRepairTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowRepairTableAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOrderTable", ReplyAction="http://tempuri.org/IService1/ShowOrderTableResponse")]
        System.Data.DataSet ShowOrderTable(string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowOrderTable", ReplyAction="http://tempuri.org/IService1/ShowOrderTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowOrderTableAsync(string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewReview", ReplyAction="http://tempuri.org/IService1/NewReviewResponse")]
        bool NewReview(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewReview", ReplyAction="http://tempuri.org/IService1/NewReviewResponse")]
        System.Threading.Tasks.Task<bool> NewReviewAsync(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowEditReview", ReplyAction="http://tempuri.org/IService1/ShowEditReviewResponse")]
        System.Data.DataSet ShowEditReview(string VIN, string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowEditReview", ReplyAction="http://tempuri.org/IService1/ShowEditReviewResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowEditReviewAsync(string VIN, string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveEditReview", ReplyAction="http://tempuri.org/IService1/SaveEditReviewResponse")]
        string SaveEditReview(CheckVinClient.WCFVIN.Review Save);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveEditReview", ReplyAction="http://tempuri.org/IService1/SaveEditReviewResponse")]
        System.Threading.Tasks.Task<string> SaveEditReviewAsync(CheckVinClient.WCFVIN.Review Save);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRepair", ReplyAction="http://tempuri.org/IService1/NewRepairResponse")]
        bool NewRepair(CheckVinClient.WCFVIN.Repair composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRepair", ReplyAction="http://tempuri.org/IService1/NewRepairResponse")]
        System.Threading.Tasks.Task<bool> NewRepairAsync(CheckVinClient.WCFVIN.Repair composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditRepair", ReplyAction="http://tempuri.org/IService1/EditRepairResponse")]
        bool EditRepair(CheckVinClient.WCFVIN.Repair composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditRepair", ReplyAction="http://tempuri.org/IService1/EditRepairResponse")]
        System.Threading.Tasks.Task<bool> EditRepairAsync(CheckVinClient.WCFVIN.Repair composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowEditRepair", ReplyAction="http://tempuri.org/IService1/ShowEditRepairResponse")]
        System.Data.DataSet ShowEditRepair(string VIN, string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowEditRepair", ReplyAction="http://tempuri.org/IService1/ShowEditRepairResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShowEditRepairAsync(string VIN, string BusinessName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewOrder", ReplyAction="http://tempuri.org/IService1/NewOrderResponse")]
        bool NewOrder(CheckVinClient.WCFVIN.Order composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewOrder", ReplyAction="http://tempuri.org/IService1/NewOrderResponse")]
        System.Threading.Tasks.Task<bool> NewOrderAsync(CheckVinClient.WCFVIN.Order composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientOptionStatus", ReplyAction="http://tempuri.org/IService1/ClientOptionStatusResponse")]
        System.Data.DataSet ClientOptionStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClientOptionStatus", ReplyAction="http://tempuri.org/IService1/ClientOptionStatusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ClientOptionStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BillSave", ReplyAction="http://tempuri.org/IService1/BillSaveResponse")]
        int BillSave(CheckVinClient.WCFVIN.Bill component);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BillSave", ReplyAction="http://tempuri.org/IService1/BillSaveResponse")]
        System.Threading.Tasks.Task<int> BillSaveAsync(CheckVinClient.WCFVIN.Bill component);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendOrderEmial", ReplyAction="http://tempuri.org/IService1/SendOrderEmialResponse")]
        bool SendOrderEmial(CheckVinClient.WCFVIN.ContractIServiceSendEmailOrder option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendOrderEmial", ReplyAction="http://tempuri.org/IService1/SendOrderEmialResponse")]
        System.Threading.Tasks.Task<bool> SendOrderEmialAsync(CheckVinClient.WCFVIN.ContractIServiceSendEmailOrder option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckVinClient_NewAccount", ReplyAction="http://tempuri.org/IService1/CheckVinClient_NewAccountResponse")]
        string CheckVinClient_NewAccount(CheckVinClient.WCFVIN.CheckVinClient_Account component);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckVinClient_NewAccount", ReplyAction="http://tempuri.org/IService1/CheckVinClient_NewAccountResponse")]
        System.Threading.Tasks.Task<string> CheckVinClient_NewAccountAsync(CheckVinClient.WCFVIN.CheckVinClient_Account component);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckVinClient_SingIn", ReplyAction="http://tempuri.org/IService1/CheckVinClient_SingInResponse")]
        bool CheckVinClient_SingIn(CheckVinClient.WCFVIN.CheckVinClient_Account component);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckVinClient_SingIn", ReplyAction="http://tempuri.org/IService1/CheckVinClient_SingInResponse")]
        System.Threading.Tasks.Task<bool> CheckVinClient_SingInAsync(CheckVinClient.WCFVIN.CheckVinClient_Account component);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CheckVinClient.WCFVIN.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CheckVinClient.WCFVIN.IService1>, CheckVinClient.WCFVIN.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authentication(string loginNamecrypt, string passwordcrypt) {
            return base.Channel.Authentication(loginNamecrypt, passwordcrypt);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticationAsync(string loginNamecrypt, string passwordcrypt) {
            return base.Channel.AuthenticationAsync(loginNamecrypt, passwordcrypt);
        }
        
        public object Fueltypeget(CheckVinClient.WCFVIN.Enums all) {
            return base.Channel.Fueltypeget(all);
        }
        
        public System.Threading.Tasks.Task<object> FueltypegetAsync(CheckVinClient.WCFVIN.Enums all) {
            return base.Channel.FueltypegetAsync(all);
        }
        
        public string getstartwork(string name) {
            return base.Channel.getstartwork(name);
        }
        
        public System.Threading.Tasks.Task<string> getstartworkAsync(string name) {
            return base.Channel.getstartworkAsync(name);
        }
        
        public System.Data.DataSet Business_employe(string login) {
            return base.Channel.Business_employe(login);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Business_employeAsync(string login) {
            return base.Channel.Business_employeAsync(login);
        }
        
        public System.Data.DataSet ShowReviewsTable(string VIN) {
            return base.Channel.ShowReviewsTable(VIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowReviewsTableAsync(string VIN) {
            return base.Channel.ShowReviewsTableAsync(VIN);
        }
        
        public System.Data.DataSet ShowRepairTable(string VIN) {
            return base.Channel.ShowRepairTable(VIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowRepairTableAsync(string VIN) {
            return base.Channel.ShowRepairTableAsync(VIN);
        }
        
        public System.Data.DataSet ShowOrderTable(string BusinessName) {
            return base.Channel.ShowOrderTable(BusinessName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowOrderTableAsync(string BusinessName) {
            return base.Channel.ShowOrderTableAsync(BusinessName);
        }
        
        public bool NewReview(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel) {
            return base.Channel.NewReview(WhoReviewsBusinessName, WhereReviewsBusinessName, Mileage, Colour, WhoReviewEmployee, Brakes, Damper, Exhaust, Convergence, light, Vin, fuel);
        }
        
        public System.Threading.Tasks.Task<bool> NewReviewAsync(string WhoReviewsBusinessName, string WhereReviewsBusinessName, string Mileage, string Colour, string WhoReviewEmployee, string Brakes, string Damper, string Exhaust, string Convergence, string light, string Vin, string fuel) {
            return base.Channel.NewReviewAsync(WhoReviewsBusinessName, WhereReviewsBusinessName, Mileage, Colour, WhoReviewEmployee, Brakes, Damper, Exhaust, Convergence, light, Vin, fuel);
        }
        
        public System.Data.DataSet ShowEditReview(string VIN, string BusinessName) {
            return base.Channel.ShowEditReview(VIN, BusinessName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowEditReviewAsync(string VIN, string BusinessName) {
            return base.Channel.ShowEditReviewAsync(VIN, BusinessName);
        }
        
        public string SaveEditReview(CheckVinClient.WCFVIN.Review Save) {
            return base.Channel.SaveEditReview(Save);
        }
        
        public System.Threading.Tasks.Task<string> SaveEditReviewAsync(CheckVinClient.WCFVIN.Review Save) {
            return base.Channel.SaveEditReviewAsync(Save);
        }
        
        public bool NewRepair(CheckVinClient.WCFVIN.Repair composite) {
            return base.Channel.NewRepair(composite);
        }
        
        public System.Threading.Tasks.Task<bool> NewRepairAsync(CheckVinClient.WCFVIN.Repair composite) {
            return base.Channel.NewRepairAsync(composite);
        }
        
        public bool EditRepair(CheckVinClient.WCFVIN.Repair composite) {
            return base.Channel.EditRepair(composite);
        }
        
        public System.Threading.Tasks.Task<bool> EditRepairAsync(CheckVinClient.WCFVIN.Repair composite) {
            return base.Channel.EditRepairAsync(composite);
        }
        
        public System.Data.DataSet ShowEditRepair(string VIN, string BusinessName) {
            return base.Channel.ShowEditRepair(VIN, BusinessName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShowEditRepairAsync(string VIN, string BusinessName) {
            return base.Channel.ShowEditRepairAsync(VIN, BusinessName);
        }
        
        public bool NewOrder(CheckVinClient.WCFVIN.Order composite) {
            return base.Channel.NewOrder(composite);
        }
        
        public System.Threading.Tasks.Task<bool> NewOrderAsync(CheckVinClient.WCFVIN.Order composite) {
            return base.Channel.NewOrderAsync(composite);
        }
        
        public System.Data.DataSet ClientOptionStatus() {
            return base.Channel.ClientOptionStatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ClientOptionStatusAsync() {
            return base.Channel.ClientOptionStatusAsync();
        }
        
        public int BillSave(CheckVinClient.WCFVIN.Bill component) {
            return base.Channel.BillSave(component);
        }
        
        public System.Threading.Tasks.Task<int> BillSaveAsync(CheckVinClient.WCFVIN.Bill component) {
            return base.Channel.BillSaveAsync(component);
        }
        
        public bool SendOrderEmial(CheckVinClient.WCFVIN.ContractIServiceSendEmailOrder option) {
            return base.Channel.SendOrderEmial(option);
        }
        
        public System.Threading.Tasks.Task<bool> SendOrderEmialAsync(CheckVinClient.WCFVIN.ContractIServiceSendEmailOrder option) {
            return base.Channel.SendOrderEmialAsync(option);
        }
        
        public string CheckVinClient_NewAccount(CheckVinClient.WCFVIN.CheckVinClient_Account component) {
            return base.Channel.CheckVinClient_NewAccount(component);
        }
        
        public System.Threading.Tasks.Task<string> CheckVinClient_NewAccountAsync(CheckVinClient.WCFVIN.CheckVinClient_Account component) {
            return base.Channel.CheckVinClient_NewAccountAsync(component);
        }
        
        public bool CheckVinClient_SingIn(CheckVinClient.WCFVIN.CheckVinClient_Account component) {
            return base.Channel.CheckVinClient_SingIn(component);
        }
        
        public System.Threading.Tasks.Task<bool> CheckVinClient_SingInAsync(CheckVinClient.WCFVIN.CheckVinClient_Account component) {
            return base.Channel.CheckVinClient_SingInAsync(component);
        }
    }
}
